module.exports = {
  app: document.getElementById('app'),
  fileDiv: document.getElementById('file-div'),
  toStart: document.getElementById('to-start'),
  rewind: document.getElementById('rewind'),
  playPause: document.getElementById('play-pause'),
  forward: document.getElementById('forward'),
  repeat: document.getElementById('repeat'),
  progressAndPosition: document.getElementById('progress-and-position'),
  progressDiv: document.getElementById('progress-div'),
  progress: document.getElementById('progress'),
  fakeProgress: document.getElementById('fake-progress'),
  progressInfo: document.getElementById('progress-info'),
  songLength: document.getElementById('song-length'),
  songPosition: document.getElementById('song-position'),
  songVolume: document.getElementById('song-volume'),
  songRate: document.getElementById('song-rate'),
  volume: document.getElementById('volume'),
  speed: document.getElementById('speed'),
  controls: document.querySelectorAll('.control')
}